### ISSUE TITLE
[fedora 34] error: ISO C++17 does not allow dynamic exception specifications

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/elaboradar#18]
Fedora 34 builds are failing because of the aforementioned error.

Full log: https://simc.arpae.it/moncic-ci/elaboradar/last/master/fedora34/build.log

see also: https://github.com/ARPA-SIMC/radarlib/issues/3

**Comment by edigiacomo** [comment]
The failure was caused by ARPA-SIMC/radarlib#3.
