### ISSUE TITLE
Riusare dati intermedi nell'elaborazione di elaboradar

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/elaboradar#3]
Al momento tutto il calcolo avviene tre volte: il medio, il corto fermandosi al beam blocking, e il corto con VPR e classificazione.

Si può ottimizzare facendo tutti i calcoli con il raggio massimo disponibile alla risoluzione nativa del radar (al momento data per scontata a 250m), e poi generando cartografia cartesiana alle risoluzioni richieste (medio e corto raggio).

La cartografia a questo punto si può generare in vari punti dell'elaborazione, per avere il corto solo col beam blocking e il corto con anche VPR e classificazione, e volendo in futuro generare facilmente anche altre mappe intermedie.

**Comment by spanezz** [comment]
Aspettiamo la risoluzione di #7 per evitare di riimplementare tutto due volte, col vecchio e col nuovo algoritmo di generazione cartografia.

**Comment by brancomat** [comment]
Risolto in daf7e9f96aeb173a4dd3573d15ee17fe4fc76f0b
