### ISSUE TITLE
Calcolo del VPR usando Eigen invece di GST

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/elaboradar#5]
Al momento GST viene usato soltanto per il calcolo del VPR. Se Eigen fornisce le stesse funzioni, possiamo passare a Eigen ed eliminare una dipendenza.

**Comment by afornasiero** [comment]
prove di oggi, compila ma ancora non funziona
[lm.zip](https://github.com/ARPA-SIMC/elaboradar/files/378464/lm.zip)

**Comment by afornasiero** [comment]
al momento la sostizuzione non sembra possibile
