### ISSUE TITLE
Verificare il nuovo algoritmo di generazione cartografia

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/elaboradar#7]
In elaboradar.cpp:298 c'è questo:

``` c++
        // Mettere a true per provare i nuovi algoritmi di generazione cartografia
        bool new_algo = false;
```

mettendo `new_algo` a true, gira con i nuovi algoritmi.

Confrontando le immagini ho notato che:
1. le immagini nuove sono di circa un pixel piú large; per quello che
   ho capito dovrebbero essere corrette quelle nuove, perché con tutti
   i test che ci ho messo dovrei essere riuscito ad ottenere una
   mappatura cartesiana piú precisa
2. la ZLR media è un po' piú scura: prima faceva la media del volume
   polare su un'immagine a risoluzione piena, e poi una media per
   scalare l'immagine, facendo la media delle medie.
   L'algoritmo nuovo invece fa la media di tutti i punti del volume
   polare che corrispondono al punto della mappa piccola, e quindi per
   ogni punto dell'immagine viene fatta un'unica media di tutti i punti
   del volume polare coinvolti. Se l'immagine nuova non è accettabile,
   reimplemento con la media delle medie.

Verifichiamo se vanno bene o se manca qualcosa, cosí possiamo passare al nuovo algoritmo e pulire  via il vecchio codice.

**Comment by spanezz** [comment]
Risolto il problema delle immagini scure in 17b4d4fd5e89c3f624f2d1f8d40c196b38cee043

**Comment by palberoni** [comment]
Risolto il problema della diversa copertura radiale tra il nuovo algoritmo e l'algoritmo precedente in d9738699e1fe12dbe0f198400cd4f75ea9fc0ad1

Alla riga 1998 di cum_bac.cpp sostituito il codice 

``` c++
 unsigned irange = (unsigned)round(cd.range(i, j));
```

con 

``` c++
 unsigned irange = (unsigned)floor(cd.range(i, j));
```

Alla riga 2039 di cum_bac.cpp  estesa la selezione dei raggi a az_max.

Corretto criterio di ricerca az_min az_max.

**Comment by palberoni** [comment]
Implementare nel nuovo algoritmo la correzione al criterio di ricerca az_min az_max

**Comment by spanezz** [comment]
In 8bfe0d226bc565753364de373f73c38a237a0ea2 we have an equivalent image, barring small differences in the averaging algorithm.

**Comment by spanezz** [comment]
Posso a questo punto procedere a togliere il vecchio algoritmo e passare tutto al nuovo.
