### ISSUE TITLE
integrazione radarcoordlib

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/elaboradar#9]
#4 abbisogna di radarcoordlib come libreria, attualmente interna (e appoggiata su [geographiclib](http://geographiclib.sourceforge.net/))

ipotesi al vaglio:
1. inclusione fra le dipendenze e spostamento su github di radarcoordlib (piace)
2. rendere radarcoordlib facoltativa via configure e aprire la fiera degli `#ifdef` (non piace)
3. valutare altre librerie per la gestione delle coordinate (quali?)

finché non la risolviamo me lo autoassegno, lo step successivo sarà impezzare @edigiacomo o @spanezz per inserimento della dipendenza nel configure

**Comment by dcesari** [comment]
Non so quali siano esattamente le esigenze di elaboradar in termini di gestione delle coordinate, ma io, da utilizzatore di qgis e dei vari (ex)Warmerdam-tools, tenderei a proporre [proj](https://github.com/OSGeo/proj.4).

**Comment by spanezz** [comment]
Concordo con Davide che lo standard per la conversione di coordinate oggigiorno è proj, che è presente direi in qualunque distribuzione. proj però fa solo conversione di coordinate, e non altri geocalcoli.

Io per prima cosa vorrei vedere cosa fa radarcoordlib, capire se serve come libreria indipendente o se ha senso incorporarla in meteosatlib, o se si può direttamente sostituire con proj, vedere quali feature di geographiclib usa, e poi rivedere le varie ipotesi.

**Comment by palberoni** [comment]
Ciao.

Intervengo sull'argomento.

La radarcoordlib gestisce varie classi e serve per gestire i calcoli per 
convertire tra le coordinate radar (azimuth, elevazione e distanza lungo 
il raggio), coordinate geografiche e coordinate in proiezione naturale 
radar (leggasi azimutale equidistante tangente al sito radar).

Si va dalla più semplice classe RadarSite  che contiene  solo le 
informazioni del sito (lat, lon altezza, altezza del sito e altezza del 
centro del fascio).

e via via si complicano.   Si passa da un punto rispetto al sito e date 
una tripletta di coordinate (in uno dei tre sistemi  radar, geografica i 
cartesiana (nell'accezzione detta sopra) ) permette di convertire tra i 
vari sistemi.

Al segmento ( espresso da ovviamente dai due estremi, ogni punto può 
essere espresso in uno dei tre sistemi ) e calcola le coordinate per 
tutti i punti del segmento   (con possibilità che siano equispaziati 
lungo il segmento o a step di azimut eccetera).

Quindi quello che fa non è solo una conversione di coordinate , ma una 
serie di calcoli sulla geodetica .
A suo tempo quando ho scritto questa lib mi sono basato sulla 
geographiclib perchè mi sembrava che la proj non permettesse di fare i 
calcoli direttamente.  Sicuramente immagino si possa trovare qualche 
altro modo per aggirare il problema .

Se volte guardare al codice della radarcoordlib sta sul nostro 
repository svn e credo sia accessibile dall'esterno. 
https://svn.smr.arpa.emr.it/radar/trunk/radarcoordlib

In senso stretto a elaboradar servono poche cose che forse si possono 
ottenere direttamente da proj.  Di fatto per la scrittura del prodotto 
bisogna fornire il bounding-box in lat,lon.  Quindi bisogna fare solo il 
calcolo per convertire una coordinata aeqd in geografica, in realta 4 
coppie [x,y] in [lat,lon](tipico lavoro di proj immagino).

Semplicemente è già tutto dentro la radarcoordlib (compreso tutti i 
metodi per il calcolo esatto delle coordinate radar tenendo conto della 
propagazione).

PP
Il 12/05/2016 15:14, Enrico Zini ha scritto:

> Concordo con Davide che lo standard per la conversione di coordinate 
> oggigiorno è proj, che è presente direi in qualunque distribuzione. 
> proj però fa solo conversione di coordinate, e non altri geocalcoli.
> 
> Io per prima cosa vorrei vedere cosa fa radarcoordlib, capire se serve 
> come libreria indipendente o se ha senso incorporarla in meteosatlib, 
> o se si può direttamente sostituire con proj, vedere quali feature di 
> geographiclib usa, e poi rivedere le varie ipotesi.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/ARPA-SIMC/elaboradar/issues/9#issuecomment-218752850

## 

PPA

---

Alberoni Pier Paolo

Unita' RadarMeteorologia, RadarPluviometria,
    Nowcasting e Reti non Convenzionali
ARPAE Emilia-Romagna  - Servizio Idro-Meteo-Clima
Viale Silvani 6, 40122, Bologna

Tel: +39 051 525930 (direct)

Tel: +39 051 649 7500 (segr.)
Fax: +39 051 649 7501 (segr.)

email: palberoni@arpa.emr.it
Web: http://www.arpa.emr.it/sim

---

**Comment by brancomat** [comment]
Dunque: dopo chiacchierata con @palberoni si diceva: elaboradar per le esigenze attuali pare possa usare agevolmente proj (e lo farà).
Nel frattempo ho migrato [radarcoordlib su github](https://github.com/ARPA-SIMC/radarcoordlib) (non seguite il link svn che lo sto rimuovendo) e ho [spostato la discussione su eventuale riscrittura appoggiandosi a proj lì](https://github.com/ARPA-SIMC/radarcoordlib/issues/1) (radarcoordlib è usata in altri sw interni)
Chiudo contestualmente questo bug.
